using System.Reflection;
using System.Text.Json;

namespace WorldsAdriftRebornGameServer.Multiplayer.Islands
{
    /// <summary>
    /// One island's authored loot-container seats, in island-local metres, as RAW
    /// surface vertices. The <see cref="LootContainers.SinkMetres"/> sink is applied
    /// at the world-entity boundary, not here.
    /// </summary>
    public sealed class ReleaseLootIsland
    {
        internal ReleaseLootIsland(string workshopId, string name, int surfaceSamples,
            int tier, IReadOnlyList<(double X, double Y, double Z)> points)
        {
            WorkshopId = workshopId;
            Name = name;
            SurfaceSamples = surfaceSamples;
            Tier = tier;
            Points = points;
        }

        /// <summary>Steam Workshop id, the join key against the runtime catalogue.</summary>
        public string WorkshopId { get; }

        public string Name { get; }

        /// <summary>
        /// The extracted surface's 8 m sample count, carried so
        /// <see cref="Loot.LootBudget"/> can be re-derived and asserted against this
        /// file's own point counts.
        /// </summary>
        public int SurfaceSamples { get; }

        /// <summary>
        /// The island's MapFile cell tier, which decides what the containers hold.
        /// Carried here so the loot roll needs no second lookup and no second source
        /// of truth about tier.
        /// </summary>
        public int Tier { get; }

        /// <summary>Container seats in island-local metres, un-sunk.</summary>
        public IReadOnlyList<(double X, double Y, double Z)> Points { get; }
    }

    /// <summary>
    /// THE AUTHORED LOOT-CONTAINER SEATS FOR THE RELEASE WORLD - 2,243 of them
    /// across all 254 islands.
    ///
    /// Retail's per-island container positions did not survive, and neither did its
    /// per-island counts. What DID survive is the rule that produced both, and that
    /// is unusual enough to be worth stating plainly: unlike trees, which retail
    /// authored by hand from editor markers and which are therefore unrecoverable in
    /// principle, loot containers were placed by an ALGORITHM the client still
    /// contains. <c>acs/IslandDataBankAndLootableSpawnerVisualizer.cs</c> is that
    /// algorithm and <c>acs/LootablePerAreaDataVisualizer.cs</c> is its budget. So
    /// these seats are not an invention in the way tree seats are - they are the
    /// same procedure, run over the same measured surfaces, with the one lost input
    /// (the nineteen tuning constants) replaced and labelled.
    ///
    /// Generated by <c>tools/world-import/generate-release-loot-placements.py</c>.
    /// <c>ReleaseLootCatalogTests</c> asserts every island's point count equals what
    /// <see cref="Loot.LootBudget"/> says and that no two seats on an island are
    /// closer than the relaxation floor, so the C# and the Python cannot drift.
    ///
    /// Two islands carry zero seats and that is honest rather than a gap: Belial
    /// (3 surface samples) and DrunkRaven Inn (100) have no pair of points that can
    /// satisfy even the relaxed spacing ladder. They are the same two islands the
    /// tree pass struggles with, for the same reason.
    /// </summary>
    public static class ReleaseLootCatalog
    {
        internal const string ResourceName = "release-loot-placements.json";

        private static IReadOnlyList<ReleaseLootIsland>? _all;
        private static Dictionary<string, ReleaseLootIsland>? _byWorkshopId;

        /// <summary>Every island's seats, in catalogue order.</summary>
        public static IReadOnlyList<ReleaseLootIsland> All => _all ??= Load();

        /// <summary>Total containers across the whole catalogue.</summary>
        public static int TotalContainers
        {
            get
            {
                int total = 0;
                foreach (ReleaseLootIsland island in All) total += island.Points.Count;
                return total;
            }
        }

        /// <summary>This island's seats, or null when it is not in the catalogue.</summary>
        public static ReleaseLootIsland? ForWorkshopId(string? workshopId)
        {
            if (string.IsNullOrEmpty(workshopId)) return null;
            if (_byWorkshopId == null)
            {
                Dictionary<string, ReleaseLootIsland> index = new(StringComparer.Ordinal);
                foreach (ReleaseLootIsland island in All) index[island.WorkshopId] = island;
                _byWorkshopId = index;
            }
            return _byWorkshopId.TryGetValue(workshopId!, out ReleaseLootIsland? found) ? found : null;
        }

        private static IReadOnlyList<ReleaseLootIsland> Load()
        {
            Assembly asm = typeof(ReleaseLootCatalog).Assembly;
            string? resource = null;
            foreach (string name in asm.GetManifestResourceNames())
            {
                if (name.EndsWith(ResourceName, StringComparison.Ordinal))
                {
                    resource = name;
                    break;
                }
            }

            if (resource == null)
            {
                throw new System.IO.FileNotFoundException(
                    "embedded loot placement table '" + ResourceName + "' not found in "
                    + asm.GetName().Name
                    + "; the release world would have no loot at all. Regenerate with "
                    + "tools/world-import/generate-release-loot-placements.py.");
            }

            using System.IO.Stream stream = asm.GetManifestResourceStream(resource)!;
            using JsonDocument document = JsonDocument.Parse(stream);

            List<ReleaseLootIsland> islands = new();
            foreach (JsonElement element in document.RootElement.GetProperty("islands").EnumerateArray())
            {
                List<(double, double, double)> points = new();
                foreach (JsonElement point in element.GetProperty("points").EnumerateArray())
                {
                    points.Add((
                        point[0].GetDouble(),
                        point[1].GetDouble(),
                        point[2].GetDouble()));
                }

                islands.Add(new ReleaseLootIsland(
                    element.GetProperty("asset").GetString()!,
                    element.GetProperty("name").GetString()!,
                    element.GetProperty("samples").GetInt32(),
                    element.GetProperty("tier").GetInt32(),
                    points));
            }

            return islands;
        }
    }
}
