using System;
using System.Collections.Generic;
using WorldsAdriftRebornGameServer.Multiplayer;
using WorldsAdriftRebornGameServer.Multiplayer.Ship;
using Xunit;

namespace WorldsAdriftRebornGameServer.Multiplayer.Tests
{
    /// <summary>
    /// Byte-format tests for <see cref="ShipPlanModel"/>. The whole point of this
    /// model is byte-exactness: if the client rejects a malformed ShipPlan the
    /// build UI shows nothing, so parity is asserted against three independent
    /// sources of truth for the same default hull.
    ///
    /// Known-good fixtures below are the verbatim hex output of
    /// docs/research/loop/data/make_hulldata.py, which is itself a transcription
    /// of the client's own ShipPlan/ShipCell/ShipSection writers. Regenerate with
    /// `python3 make_hulldata.py` and compare the corresponding variant line.
    /// </summary>
    public class ShipPlanModelTests
    {
        // make_hulldata.py "one_cell"  (== ShipHull.MinimumHullData, 39 bytes)
        private const string OneCellHex =
            "010000000000e80000180000e800001800000000000001e80000180000e8000018000000000000";

        // make_hulldata.py "three_cells"  (3x1, 81 bytes)
        private const string ThreeCellsHex =
            "030000000000e80000180000e800001800000000000001e80000180000e800001800000000000001" +
            "000000e80000180000e80000180000000000000002000000e80000180000e800001800000000000000";

        // make_hulldata.py "three_by_two"  (3x2, 160 bytes)
        private const string ThreeByTwoHex =
            "060000000000e80000180000e800001800000000000001e80000180000e800001800000000000001" +
            "000000e80000180000e80000180000000000000002000000e80000180000e80000180000000000000" +
            "000000100e80000180000e800001800000000000001e80000180000e800001800000000000001000100" +
            "e80000180000e80000180000000000000002000100e80000180000e800001800000000000000";

        private static byte[] Hex(string hex)
        {
            var bytes = new byte[hex.Length / 2];
            for (int i = 0; i < bytes.Length; i++)
            {
                bytes[i] = Convert.ToByte(hex.Substring(i * 2, 2), 16);
            }
            return bytes;
        }

        // (a) Decode(MinimumHullData) succeeds and Encode() reproduces it byte-for-byte.
        [Fact]
        public void Decode_MinimumHullData_ReEncodesByteForByte()
        {
            byte[] original = ShipHull.MinimumHullData();
            Assert.Equal(ShipHull.MinimumHullDataLength, original.Length);

            ShipPlanModel model = ShipPlanModel.Decode(original);

            Assert.Single(model.Cells);
            ShipCellModel cell = model.Cells[0];
            Assert.Equal(0, cell.CellNumber);
            Assert.Equal(0, cell.DeckNumber);
            Assert.NotNull(cell.Back); // single cell has no astern neighbour -> Back written

            Assert.Equal(original, model.Encode());
        }

        // (c) Parity with make_hulldata.py: MakeDefaultStarterHull() == one_cell fixture
        //     == ShipHull.MinimumHullData(). Same 39 bytes from all three sources.
        [Fact]
        public void MakeDefaultStarterHull_MatchesPythonAndMinimumHullData()
        {
            byte[] fixture = Hex(OneCellHex);

            Assert.Equal(fixture, ShipHull.MinimumHullData());
            Assert.Equal(fixture, ShipPlanModel.MakeDefaultStarterHull().Encode());
        }

        // (c) Parity with make_hulldata.py for the multi-cell variants: decode the
        //     Python-generated bytes and re-encode identically.
        [Theory]
        [InlineData(OneCellHex, 1)]
        [InlineData(ThreeCellsHex, 3)]
        [InlineData(ThreeByTwoHex, 6)]
        public void Decode_PythonFixtures_RoundTripByteForByte(string hex, int expectedCells)
        {
            byte[] fixture = Hex(hex);

            ShipPlanModel model = ShipPlanModel.Decode(fixture);

            Assert.Equal(expectedCells, model.Cells.Count);
            Assert.Equal(fixture, model.Encode());
        }

        // (b) Round-trip of a hand-built multi-part plan with non-default geometry.
        [Fact]
        public void HandBuiltMultiPartPlan_RoundTrips()
        {
            var plan = new ShipPlanModel();

            // Cell 0: curved, asymmetric section, with a Back.
            var front0 = ShipSectionModel.MakeDefault(4.5f);
            front0.Top[0] = new ShipVertexModel(-5f, 0.4f, 0.6f);
            front0.Top[1] = new ShipVertexModel(5f, 0.4f, -0.6f);
            front0.Curve[0, 0] = 0.5f;
            front0.Curve[1, 1] = -0.75f;
            var back0 = ShipSectionModel.MakeDefault(2f);
            plan.Cells.Add(new ShipCellModel(0, 0, front0, back0));

            // Cell 1: forward neighbour of cell 0, so NO Back on the wire.
            var front1 = ShipSectionModel.MakeDefault(3.25f);
            front1.Bottom[0] = new ShipVertexModel(-3.25f, -0.5f, 0.25f);
            plan.Cells.Add(new ShipCellModel(1, 0, front1, back: null));

            // Cell on deck 1.
            plan.Cells.Add(new ShipCellModel(0, 1, ShipSectionModel.MakeDefault(), ShipSectionModel.MakeDefault()));

            byte[] encoded = plan.Encode();

            ShipPlanModel decoded = ShipPlanModel.Decode(encoded);
            Assert.Equal(encoded, decoded.Encode());

            // Structure survived: cell 1 still has no Back, deck-1 cell present.
            Assert.Equal(3, decoded.Cells.Count);
            Assert.Null(decoded.Cells[1].Back);
            Assert.Equal(1, decoded.Cells[2].DeckNumber);

            // Geometry quantised but stable across a second trip (bytes identical).
            Assert.Equal(encoded, ShipPlanModel.Decode(decoded.Encode()).Encode());
        }

        // Encoded length is a pure function of structure: 2 header + per-cell
        // (4 + 16 + 1 [+16 if Back]).
        [Fact]
        public void EncodedLength_IsStructural()
        {
            var withBack = new ShipPlanModel();
            withBack.Cells.Add(new ShipCellModel(0, 0, ShipSectionModel.MakeDefault(), ShipSectionModel.MakeDefault()));
            Assert.Equal(39, withBack.Encode().Length); // 2 + 37

            var noBack = new ShipPlanModel();
            noBack.Cells.Add(new ShipCellModel(0, 0, ShipSectionModel.MakeDefault(), back: null));
            Assert.Equal(23, noBack.Encode().Length); // 2 + 21

            Assert.Equal(2, new ShipPlanModel().Encode().Length); // empty plan: just the count
        }

        // (d) Malformed / truncated input must fail cleanly - no throw out of TryDecode.
        [Fact]
        public void TryDecode_Null_FailsCleanly()
        {
            Assert.False(ShipPlanModel.TryDecode(null, out var model, out var error));
            Assert.Null(model);
            Assert.False(string.IsNullOrEmpty(error));
        }

        [Fact]
        public void TryDecode_Empty_FailsCleanly()
        {
            Assert.False(ShipPlanModel.TryDecode(Array.Empty<byte>(), out var model, out var error));
            Assert.Null(model);
            Assert.False(string.IsNullOrEmpty(error));
        }

        [Fact]
        public void TryDecode_Truncated_FailsCleanly()
        {
            // Claims 1 cell but cut off mid-section.
            byte[] full = ShipHull.MinimumHullData();
            var truncated = new byte[20];
            Array.Copy(full, truncated, 20);

            Assert.False(ShipPlanModel.TryDecode(truncated, out var model, out var error));
            Assert.Null(model);
            Assert.False(string.IsNullOrEmpty(error));
        }

        [Fact]
        public void TryDecode_ClaimsMoreCellsThanBytes_FailsCleanly()
        {
            // header says 99 cells, no body follows.
            byte[] lying = { 99, 0 };
            Assert.False(ShipPlanModel.TryDecode(lying, out var model, out var error));
            Assert.Null(model);
            Assert.False(string.IsNullOrEmpty(error));
        }

        [Fact]
        public void TryDecode_ValidBlob_Succeeds()
        {
            Assert.True(ShipPlanModel.TryDecode(ShipHull.MinimumHullData(), out var model, out var error));
            Assert.NotNull(model);
            Assert.Null(error);
        }

        // The quantiser must not emit the one value that would break the round trip.
        [Fact]
        public void Quantiser_NeverProducesUnrecoverableMinus128()
        {
            var plan = new ShipPlanModel();
            var s = ShipSectionModel.MakeDefault();
            // Out-of-range values clamp; must still survive re-encode.
            s.Top[0] = new ShipVertexModel(-9999f, -9999f, -9999f);
            s.Top[1] = new ShipVertexModel(9999f, 9999f, 9999f);
            plan.Cells.Add(new ShipCellModel(0, 0, s, back: null));

            byte[] encoded = plan.Encode();
            Assert.Equal(encoded, ShipPlanModel.Decode(encoded).Encode());
        }
    }
}
